# Ejercicio

Bibliotecas a importar

In [49]:
import pandas as pd
pd.set_option('display.max_rows', 15)
pd.set_option('display.max_columns', 15)

import os

Subir la base datos

In [50]:
# Paso 1: Crear carpeta para almacenar datos en crudo
os.makedirs('./data/raw', exist_ok=True)

# Paso 2: Descargar y almacenar el archivo
url = "https://raw.githubusercontent.com/4GeeksAcademy/decision-tree-project-tutorial/main/diabetes.csv"
file_path = './data/raw/diabetes.csv'
df = pd.read_csv(url)

# Guardar una copia local en la carpeta indicada
df.to_csv(file_path, index=False)

# Paso 3: Cargar el conjunto de datos
# Verificamos las primeras filas para inspeccionar la estructura y composici√≥n del conjunto de datos
df = pd.read_csv(file_path)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Conociendo el Data Set

In [51]:
# Obtener las dimensiones
print("Filas , Columnas")
df.shape

Filas , Columnas

(768, 9)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [53]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [54]:
tipo_de_datos = pd.DataFrame(df.dtypes)
tipo_de_datos

                                0
Pregnancies                 int64
Glucose                     int64
BloodPressure               int64
SkinThickness               int64
Insulin                     int64
BMI                       float64
DiabetesPedigreeFunction  float64
Age                         int64
Outcome                     int64

##### Diccionario de variables  
- __Pregnancies__. N√∫mero de embarazos del paciente (num√©rico)
- __Glucose__. Concentraci√≥n de glucosa en plasma a las 2 horas de un test de tolerancia oral a la glucosa (num√©rico)
- __BloodPressure__. Presi√≥n arterial diast√≥lica (medida en mm Hg) (num√©rico)
- __SkinThickness__. Grosor del pliegue cut√°neo del tr√≠ceps (medida en mm) (num√©rico)
- __Insulin__. Insulina s√©rica de 2 horas (medida en mu U/ml) (num√©rico)
- __BMI__. √çndice de masa corporal (num√©rico)
- __DiabetesPedigreeFunction__. Funci√≥n de pedigr√≠ de diabetes (num√©rico)
- __Age__. Edad del paciente (num√©rico)
- __Outcome__. Variable de clase (0 o 1), siendo 0 negativo en diabetes y 1, positivo (num√©rico)

In [55]:
# Identificar las variables num√©ricas
variables_numericas = df._get_numeric_data().columns
print("Las variables num√©ricas son:")
for var in variables_numericas:
    print(f" - {var}")

# Identificar las variables categ√≥ricas
variables_categoricas = df.select_dtypes(include=['object']).columns
print("\nLas variables categ√≥ricas son:")
for var in variables_categoricas:
    print(f" - {var}")

Las variables num√©ricas son:
 - Pregnancies
 - Glucose
 - BloodPressure
 - SkinThickness
 - Insulin
 - BMI
 - DiabetesPedigreeFunction
 - Age
 - Outcome

Las variables categ√≥ricas son: